 services:
  issuer:
    image: acapy-test
    ports:
      - "3001:3001"
    command: >
      start
        --label Issuer
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://issuer:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --tails-server-base-url http://tails:6543
        --wallet-type askar-anoncreds
        --wallet-name agency
        --wallet-key insecure
        --auto-provision
        --log-level debug
        --debug-webhooks
        --no-ledger
        --notify-revocation
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5
    depends_on:
      tails:
        condition: service_started

  holder:
    image: acapy-test
    ports:
      - "3002:3001"
    command: >
      start
        --label Holder
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://holder:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --wallet-type askar-anoncreds
        --wallet-name holder
        --wallet-key insecure
        --auto-provision
        --log-level debug
        --debug-webhooks
        --no-ledger
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5

  example:
    container_name: controller
    build:
      context: ../..
    environment:
      - ISSUER=http://issuer:3001
      - HOLDER=http://holder:3001
    volumes:
      - ./example.py:/usr/src/app/example.py:ro,z
    command: python -m example
    depends_on:
      issuer:
        condition: service_healthy
      holder:
        condition: service_healthy

  tails:
    image: ghcr.io/bcgov/tails-server:latest
    ports:
      - 6543:6543
    environment:
      - GENESIS_URL=http://test.bcovrin.vonx.io/genesis
    command: >
      tails-server
      --host 0.0.0.0
      --port 6543
      --storage-path /tmp/tails-files
      --log-level info


